version: '3.4'

services:
  employees.api:
    image: ${DOCKER_REGISTRY-}employeesapi
    build:
      context: .
      dockerfile: Employees.Api/Dockerfile

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
  ms-sql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word1"
    ports:
      - "1433:1433"

 